---

# disable search update in wiki-specific settings
- name: Disable search update for {{ wiki_id }}
  copy:
    src: "files/disable-search-update.php"
    dest: "{{ m_local_app }}/wikis/{{ wiki_id }}/postLocalSettings.d/disable-search-update.php"
    owner: apache
    group: apache
    mode: 755

- name: Destroy current search index for {{ wiki_id }}
  shell: >
    WIKI="{{ wiki_id }}"
    php "{{ m_mediawiki }}/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php"
    --startOver
    > {{ m_logs }}/search-index0.{{ wiki_id }}.{{ ansible_date_time.iso8601 }}.log
  run_once: true
  async: "{{ m_search_index_async_length | int }}"
  poll: "{{ m_search_index_poll | int }}"
  # Ignore errors to be sure the next command runs, re-enabling search update
  ignore_errors: yes
  register: index1

# FIXME: add notifications on failures


# Remove search-update disable in wiki-specific settings
- name: Re-enable search update for {{ wiki_id }}
  file:
    path: "{{ m_local_app }}/wikis/{{ wiki_id }}/postLocalSettings.d/disable-search-update.php"
    state: absent


# Bootstrap the search index
#
# Note that this can take some time
# For large wikis read "Bootstrapping large wikis" in https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FCirrusSearch.git/REL1_25/README
- name: Indexing part 1 for {{ wiki_id }}
  shell: >
    WIKI="{{ wiki_id }}"
    php "{{ m_mediawiki }}/extensions/CirrusSearch/maintenance/forceSearchIndex.php"
    --skipLinks --indexOnSkip
    > {{ m_logs }}/search-index1.{{ wiki_id }}.{{ ansible_date_time.iso8601 }}.log
  run_once: true
  async: "{{ m_search_index_async_length | int }}"
  poll: "{{ m_search_index_poll | int }}"
  ignore_errors: yes
  register: index2

# FIXME: add notifications on failures

- name: Indexing part 2 for {{ wiki_id }}
  shell: >
    WIKI="{{ wiki_id }}"
    php "{{ m_mediawiki }}/extensions/CirrusSearch/maintenance/forceSearchIndex.php"
    --skipParse
    > {{ m_logs }}/search-index2.{{ wiki_id }}.{{ ansible_date_time.iso8601 }}.log
  run_once: true
  async: "{{ m_search_index_async_length | int }}"
  poll: "{{ m_search_index_poll | int }}"
  ignore_errors: yes
  register: index3

# FIXME: add notifications on failures

# FIXME: add notifications on complete
